Updating networking script
Signed-off-by: Mobin <mobin@mobintestserver.ir>

diff --git a/scripts/networking b/scripts/networking
--- a/scripts/networking
+++ b/scripts/networking
@@ -1,13 +1,10 @@
 #!/bin/sh -e
-### BEGIN INIT INFO
-# Provides:          networking ifupdown
-# Required-Start:    mountkernfs $local_fs urandom
-# Required-Stop:     $local_fs
-# Default-Start:     S
-# Default-Stop:      0 6
-# Short-Description: Raise network interfaces.
-# Description:       Prepare /run/network directory, ifstate file and raise network interfaces, or take them down.
-### END INIT INFO
+
+## Debian/Devuan networking/ifupdown script for Dinit
+## Based on Debian/Devuan networking/ifupdown sysvinit script
+## Author: Mobin Aydinfar <mobin@mobintestserver.ir>
+## LISENCE: GPLv3 or later
+## Copyright (C) 2022 Dinit for Devuan project: https://git.mobintestserver.ir/Dinit_on_Devuan
 
 PATH="/sbin:/bin"
 RUN_DIR="/run/network"
@@ -17,7 +14,8 @@ STATEDIR="$RUN_DIR/state"
 [ -x /sbin/ifup ] || exit 0
 [ -x /sbin/ifdown ] || exit 0
 
-. /lib/lsb/init-functions
+## No need more. DONT USE LSB VARS
+#. /lib/lsb/init-functions
 
 CONFIGURE_INTERFACES=yes
 EXCLUDE_INTERFACES=
@@ -40,22 +38,22 @@ process_exclusions() {
 
 process_options() {
     [ -e /etc/network/options ] || return 0
-    log_warning_msg "/etc/network/options still exists and it will be IGNORED! Please use /etc/sysctl.conf instead."
+    echo $(date -u) "[WARN] /etc/network/options still exists and it will be IGNORED! Please use /etc/sysctl.conf instead."
 }
 
 check_ifstate() {
     if [ ! -d "$RUN_DIR" ] ; then
 	if ! mkdir -p "$RUN_DIR" ; then
-	    log_failure_msg "can't create $RUN_DIR"
+	    echo $(date -u) "[ERR] can't create $RUN_DIR" >> /dev/stderr
 	    exit 1
 	fi
 	if ! chown root:netdev "$RUN_DIR" ; then
-	    log_warning_msg "can't chown $RUN_DIR"
+	    echo $(date -u) "[WARN] can't chown $RUN_DIR"
 	fi
     fi
     if [ ! -r "$IFSTATE" ] ; then
 	if ! :> "$IFSTATE" ; then
-	    log_failure_msg "can't initialise $IFSTATE"
+	    echo $(date -u) "[ERR] can't initialise $IFSTATE" >> /dev/stderr
 	    exit 1
 	fi
     fi
@@ -65,20 +63,20 @@ check_network_file_systems() {
     [ -e /proc/mounts ] || return 0
 
     if [ -e /etc/iscsi/iscsi.initramfs ]; then
-	log_warning_msg "not deconfiguring network interfaces: iSCSI root is mounted."
+	echo $(date -u) "[WARN] not deconfiguring network interfaces: iSCSI root is mounted."
 	exit 0
     fi
 
     while read DEV MTPT FSTYPE REST; do
 	case $DEV in
 	/dev/nbd*|/dev/nd[a-z]*|/dev/etherd/e*|curlftpfs*)
-	    log_warning_msg "not deconfiguring network interfaces: network devices still mounted."
+	    echo $(date -u) "[WARN] not deconfiguring network interfaces: network devices still mounted."
 	    exit 0
 	    ;;
 	esac
 	case $FSTYPE in
 	nfs|nfs4|smbfs|ncp|ncpfs|cifs|coda|ocfs2|gfs|pvfs|pvfs2|fuse.httpfs|fuse.curlftpfs)
-	    log_warning_msg "not deconfiguring network interfaces: network file systems still mounted."
+	    echo $(date -u) "[WARN] not deconfiguring network interfaces: network file systems still mounted."
 	    exit 0
 	    ;;
 	esac
@@ -91,7 +89,7 @@ check_network_swap() {
     while read DEV MTPT FSTYPE REST; do
 	case $DEV in
 	/dev/nbd*|/dev/nd[a-z]*|/dev/etherd/e*)
-	    log_warning_msg "not deconfiguring network interfaces: network swap still mounted."
+	    echo $(date -u) "[WARN] not deconfiguring network interfaces: network swap still mounted."
 	    exit 0
 	    ;;
 	esac
@@ -124,12 +122,12 @@ start)
 
 	if [ "$CONFIGURE_INTERFACES" = no ]
 	then
-	    log_action_msg "Not configuring network interfaces, see /etc/default/networking"
+	    echo $(date -u) "[WARN] Not configuring network interfaces, see /etc/default/networking"
 	    exit 0
 	fi
 	set -f
 	exclusions=$(process_exclusions)
-	log_action_begin_msg "Configuring network interfaces"
+	echo $(date -u) "[INFO] Configuring network interfaces..."
 	if [ -x /bin/udevadm ]; then
 		if [ -n "$(ifquery --list --exclude=lo)" ] || [ -n "$(ifquery --list --allow=hotplug)" ]; then
 			/bin/udevadm settle || true
@@ -137,9 +135,9 @@ start)
 	fi
 	if ifup -a $exclusions $verbose && ifup_hotplug $exclusions $verbose
 	then
-	    log_action_end_msg $?
+	    echo $(date -u) "[INFO] Configuring network interfaces has return $?"
 	else
-	    log_action_end_msg $?
+	    echo $(date -u) "[ERR] Configuring network interfaces has return $?"
 	fi
 	;;
 
@@ -147,45 +145,45 @@ stop)
 	check_network_file_systems
 	check_network_swap
 
-	log_action_begin_msg "Deconfiguring network interfaces"
+	echo $(date -u) "[INFO] Deconfiguring network interfaces..."
 	if ifdown -a --exclude=lo $verbose; then
-	    log_action_end_msg $?
+	    echo $(date -u) "[INFO] Deconfiguring network interfaces has return $?"
 	else
-	    log_action_end_msg $?
+	    echo $(date -u) "[ERR] Deconfiguring network interfaces has return $?"
 	fi
 	;;
 
-reload)
-	process_options
+#reload)
+#	process_options
+#
+#	echo $(date -u)"[INFO] Reloading network interfaces configuration"
+#	state=$(ifquery --state)
+#	ifdown -a --exclude=lo $verbose || true
+#	if ifup --exclude=lo $state $verbose ; then
+#	    log_action_end_msg $?
+#	else
+#	    log_action_end_msg $?
+#	fi
+#	;;
 
-	log_action_begin_msg "Reloading network interfaces configuration"
-	state=$(ifquery --state)
-	ifdown -a --exclude=lo $verbose || true
-	if ifup --exclude=lo $state $verbose ; then
-	    log_action_end_msg $?
-	else
-	    log_action_end_msg $?
-	fi
-	;;
-
-force-reload|restart)
-	process_options
-
-	log_warning_msg "Running $0 $1 is deprecated because it may not re-enable some interfaces"
-	log_action_begin_msg "Reconfiguring network interfaces"
-	ifdown -a --exclude=lo $verbose || true
-	set -f
-	exclusions=$(process_exclusions)
-	if ifup -a --exclude=lo $exclusions $verbose && ifup_hotplug $exclusions $verbose
-	then
-	    log_action_end_msg $?
-	else
-	    log_action_end_msg $?
-	fi
-	;;
+#force-reload|restart)
+#	process_options
+#
+#	log_warning_msg "Running $0 $1 is deprecated because it may not re-enable some interfaces"
+#	log_action_begin_msg "Reconfiguring network interfaces"
+#	ifdown -a --exclude=lo $verbose || true
+#	set -f
+#	exclusions=$(process_exclusions)
+#	if ifup -a --exclude=lo $exclusions $verbose && ifup_hotplug $exclusions $verbose
+#	then
+#	    log_action_end_msg $?
+#	else
+#	    log_action_end_msg $?
+#	fi
+#	;;
 
 *)
-	echo "Usage: /etc/init.d/networking {start|stop|reload|restart|force-reload}"
+	echo "Usage: /etc/dinit.d/scripts/networking networking/ifupdown script for Debina/Devuan with Dinit. DONT USE IT DIRECTLY! using dinitctl(8) for controling networking service"
 	exit 1
 	;;
 esac
